---

- name: Upgrade all packages (Might take a few minutes)
  tags: ansible-lint
  become: yes
  apt:
    update_cache: yes

- name: Install default packages
  tags: ansible-lint
  become: yes
  package:
    name: "ansible-lint"
    state: latest
