---

- name: Install default-jdk
  become: yes
  tags: tomcat
  package:
    name: default-jdk
    state: present

- name: Install tomcat
  tags: tomcat
  get_url:
    url: "{{ tomcat_download_url }}"
    dest: /tmp
    owner: "{{ username }}"
    group: "{{ groupname }}"

- name: Extract tomcat
  tags: tomcat
  unarchive:
    src: /tmp/apache-tomcat-{{ tomcat_version }}.tar.gz
    dest: "{{ homedir }}/Tools/"
    owner: "{{ username }}"
    group: "{{ groupname }}"

- name: Create tomcat link
  tags: tomcat
  file:
    src: "{{ homedir }}/Tools/apache-tomcat-{{ tomcat_version }}"
    dest: "{{ homedir }}/Tools/tomcat"
    state: link
    owner: "{{ username }}"
    group: "{{ groupname }}"

- name: Get postgresql jdbc
  tags: tomcat
  get_url:
    url: "{{ jdbc_postgresql_download_url }}"
    dest: "{{ homedir }}/Tools/tomcat/lib"
    owner: "{{ username }}"
    group: "{{ groupname }}"
