---

- name: Add apt key
  become: true
  tags: chrome
  register: task_result
  retries: "{{ RETRIES }}"
  delay: "{{ DELAY }}"
  until: task_result is success
  apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    state: present

- name: Add google repository
  become: true
  tags: chrome
  register: task_result
  retries: "{{ RETRIES }}"
  delay: "{{ DELAY }}"
  until: task_result is success
  apt_repository:
    repo: deb http://dl.google.com/linux/chrome/deb/ stable main
    state: present

- name: Update apt packages
  tags: chrome
  become: true
  apt:
    update_cache: yes

- name: Install Google Chrome
  become: true
  tags: chrome
  package:
    name: google-chrome-stable
    state: present

- name: Rmove obsolete file
  become: true
  tags: chrome
  file: 
    path: /etc/apt/sources.list.d/dl_google_com_linux_chrome_deb.list
    state: absent