---

- name: Install default jdk
  tags: java
  become: yes
  package:
    name: default-jdk
    state: present

- name: Download Java 11
  tags: java
  register: task_result
  retries: "{{ RETRIES }}"
  delay: "{{ DELAY }}"
  get_url:
    url: "https://download.java.net/java/GA/jdk11/28/GPL/openjdk-11+28_linux-x64_bin.tar.gz"
    dest: "/tmp/openjdk-11+28_linux-x64_bin.tar.gz"
  until: "'OK' in task_result.msg or 'file already exists' in task_result.msg or 'HTTP Error 304: Not Modified' in task_result.msg"

- name: Extract Java
  become: yes
  tags: java
  unarchive:
    src: "/tmp/openjdk-11+28_linux-x64_bin.tar.gz"
    dest: /usr/lib/jvm
    owner: "{{ USERNAME }}"
    group: "{{ GROUPNAME }}"

- name: Update java alternatives
  become: yes
  tags: java
  command: "{{ item }}"
  with_items:
  - "sh -c 'for bin in /usr/lib/jvm/jdk-11/bin/*; do update-alternatives --install /usr/bin/$(basename $bin) $(basename $bin) $bin 100; done'"
  - "sh -c 'for bin in /usr/lib/jvm/jdk-11/bin/*; do update-alternatives --set $(basename $bin) $bin; done'"
