---

- name: Download Ubuntu dropbox package
  tags: dropbox
  register: task_result
  retries: "{{ RETRIES }}"
  delay: "{{ DELAY }}"
  get_url: 
    url: "{{ dropbox_url_ubuntu_deb }}"
    dest: "{{ dropbox_tmp_deb }}"
  until: "'OK' in task_result.msg or 'file already exists' in task_result.msg or 'HTTP Error 304: Not Modified' in task_result.msg"

- name: Install Ubuntu dropbox package
  tags: dropbox
  become: yes
  apt: 
    deb: "{{dropbox_tmp_deb}}"