---

- name: Set timezone
  become: yes
  tags: common
  timezone:
    name: Europe/Amsterdam

- name: Create root directories
  become: yes
  tags: common
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
  - "/usr/share/applications/"

- name: "Create {{ USERNAME }} directories"
  tags: common
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: "{{ USERNAME }}"
    group: "{{ GROUPNAME }}"
  with_items:
  - "{{ HOMEDIR }}/.ssh/"
  - "{{ HOMEDIR }}/Desktop/"
  - "{{ HOMEDIR }}/Tools"
  - "{{ HOMEDIR }}/.gnome/apps/"
  - "{{ HOMEDIR }}/.local/share/applications/"
  - "{{ HOMEDIR }}/sources/"

#- name: Install draw.io
#  snap:
#    name: drawio
#    classic: yes
