---

- name: Find latest version
  tags: intellij
  retries: "{{ RETRIES }}"
  delay: "{{ DELAY }}"
  until: intellij_releases_response.rc == 0
  uri:
    url: "https://data.services.jetbrains.com/products/releases?code=IIU%2CIIC&latest=true&type=release"
    return_content: yes
    validate_certs: no
    body_format: json
  register: intellij_releases_response
  when: intellij_version == 'latest'

- name: Set intellij version
  set_fact:
    intellij_version: "{{ intellij_releases_response.json.IIC.0.version }}"
  when: intellij_version == 'latest'
  tags: intellij

- name: "Download intellij {{ intellij_version }} ..."
  tags: intellij
  register: task_result
  retries: "{{ RETRIES }}"
  delay: "{{ DELAY }}"
  get_url:
    url: "{{intellij_url}}"
    dest: "{{intellij_tmp}}"
  until: "'OK' in task_result.msg or 'file already exists' in task_result.msg or 'HTTP Error 304: Not Modified' in task_result.msg"

- name: Ensure directory exists
  tags: intellij
  file:
    path: "{{ intellij_install_dir }}"
    state: directory
    owner: "{{ USERNAME }}"
    group: "{{ GROUPNAME }}"

- name: Unarchive intellij
  tags: intellij
  unarchive:
    src: "{{intellij_tmp}}"
    dest: "{{intellij_install_dir}}"
    owner: "{{ USERNAME }}"
    group: "{{ GROUPNAME }}"

- name: Retreive intellij dir name
  tags: intellij
  command: ls -t {{intellij_install_dir}}
  register: result_intellij_folder_name

- name: Ensure intellij is configured
  tags: intellij
  template:
    src: idea.properties.j2
    dest: "{{intellij_install_dir}}/{{intellij_folder_name}}/bin/idea.properties"
    owner: "{{ USERNAME }}"
    group: "{{ GROUPNAME }}"

- name: Ensure intellij bin exist
  become: yes
  tags: intellij
  template:
    src: intellij.j2
    dest: /usr/bin/intellij
    mode: 0755

- name: Ensure that a desktop shortcut for intellij exists
  tags: intellij
  template:
    src: intellij.desktop.j2
    dest: "{{ item }}"
    mode: 0755
    owner: "{{ USERNAME }}"
    group: "{{ GROUPNAME }}"
  with_items:
  - "{{ HOMEDIR }}/Desktop/intellij.desktop"
  - "{{ HOMEDIR }}/.gnome/apps/intellij.desktop"
