---

- name: Install required package
  tags: ansible
  become: true
  ansible.builtin.package:
    name: python3-pip
    state: present

- name: Update to latest pip3
  tags: ansible
  become: true
  ansible.builtin.pip:
    name: pip
    state: present
    extra_args: --upgrade
    executable: pip3

- name: Install ansible
  tags: ansible, molecule
  become: true
  ansible.builtin.pip:
    name: "{{ item }}"
    state: present
  loop:
  - ansible
  - molecule
  - molecule-azure
  - molecule-docker