---
- name: Ensure directory exists
  tags: autologin
  become: true
  file:
    dest: /etc/lightdm/lightdm.conf.d
    state: directory

- name: Enable auto login for user {{ USERNAME }}
  tags: autologin
  become: true
  copy:
    dest: /etc/lightdm/lightdm.conf.d/42-autologin.conf
    content: |
      [SeatDefaults]
      autologin-user={{ USERNAME }}
