---
- name: Ensure directory exists
  tags: autologin
  become: yes
  file:
    dest: /etc/lightdm/lightdm.conf.d
    state: directory

- name: Enable auto login for user vagrant
  tags: autologin
  become: yes
  copy:
    dest: /etc/lightdm/lightdm.conf.d/42-autologin.conf
    content: |
      [SeatDefaults]
      autologin-user={{ username }}
