---

- name: Create directory
  tags: eclipse
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ USERNAME }}"
    group: "{{ GROUPNAME }}"
  with_items:
  - "{{ HOMEDIR }}/Tools/eclipse-{{ eclipse_release }}"
  - "{{ HOMEDIR }}/eclipse-workspace"

- name: "Download eclipse {{ eclipse_release }} ..."
  tags: eclipse
  register: task_result
  retries: "{{ RETRIES }}"
  delay: "{{ DELAY }}"
  get_url:
    url: "{{ eclipse_download_url }}"
    dest: "{{ HOMEDIR }}/Tools/eclipse.tar.gz"
    owner: "{{ USERNAME }}"
    group: "{{ GROUPNAME }}"
  until: "'OK' in task_result.msg or 'file already exists' in task_result.msg or 'HTTP Error 304: Not Modified' in task_result.msg"

- name: Remove previous installation
  tags: eclipse
  file:
    dest: "{{ HOMEDIR }}/Tools/eclipse-{{ eclipse_release }}"
    state: directory

- name: Unpack eclipse
  tags: eclipse
  unarchive:
    src: "{{ homedir }}/Tools/eclipse.tar.gz"
    dest: "{{ HOMEDIR }}/Tools/eclipse-{{ eclipse_release }}"
    extra_opts: "--strip-components=1"
    owner: "{{ USERNAME }}"
    group: "{{ GROUPNAME }}"

- name: Ensure link exists
  tags: eclipse
  file:
    src: "{{ HOMEDIR }}/Tools/eclipse-{{ eclipse_release }}"
    dest: "{{ HOMEDIR }}/Tools/eclipse"
    state: link
    owner: "{{ USERNAME }}"
    group: "{{ GROUPNAME }}"

- name: Configure eclipse ini configuration (Xms)
  tags: eclipse
  lineinfile:
    regexp: "^-Xms256m"
    line: "-Xms2G"
    dest: "{{ eclipse_home }}/eclipse.ini"

- name: Configure eclipse ini configuration (Xmx)
  tags: eclipse
  lineinfile:
    regexp: "^-Xmx1024m"
    line: "-Xmx2G"
    dest: "{{ eclipse_home }}/eclipse.ini"

- name: Ensure that a desktop shortcut for eclipse exists
  tags: eclipse
  template:
    src: eclipse.desktop.j2
    dest: "{{ item }}"
    mode: 0755
    owner: "{{ USERNAME }}"
    group: "{{ GROUPNAME }}"
  with_items:
  - "{{ HOMEDIR }}/Desktop/eclipse.desktop"
  - "{{ HOMEDIR }}/.gnome/apps/eclipse.desktop"

- name: Install lessc
  become: yes
  npm:
    name: "less"
    state: present
    global: yes

- name: Install eclipse features
  tags: eclipse, eclipse-features
  register: task_result
  retries: "{{ RETRIES }}"
  delay: "{{ DELAY }}"
  until: task_result.rc == 0
  command: "{{ eclipse_home }}/eclipse -application org.eclipse.equinox.p2.director -noSplash -repository {{ item.repo }} -installIUs {{ item.feature }}"
  with_items:
  # Cucumber
  - { repo: 'http://cucumber.github.io/cucumber-eclipse/update-site', feature: 'cucumber.eclipse.feature.feature.group' }
  - { repo: 'https://otto.takari.io/content/sites/m2e.extras/m2eclipse-mavenarchiver/0.17.2/N/LATEST/', feature: 'org.sonatype.m2e.mavenarchiver.feature.feature.group' }
  - { repo: 'http://eclipse-cs.sourceforge.net/update', feature: 'net.sf.eclipsecs.feature.group' }
  - { repo: 'http://findbugs.cs.umd.edu/eclipse', feature: 'edu.umd.cs.findbugs.plugin.eclipse.feature.group' }
  - { repo: 'http://www.sonarlint.org/eclipse', feature: 'org.sonarlint.eclipse.feature.feature.group' }
  #- { repo: 'http://coderplus.com/m2e-update-sites/jaxws-maven-plugin/', feature: 'com.coderplus.m2e.jaxwscore' }
  - { repo: 'https://repository.sonatype.org/content/repositories/forge-sites/m2e-extras/0.15.0/N/0.15.0.201206251206/', feature: 'org.sonatype.m2e.buildhelper' }
  - { repo: 'http://www.mihai-nita.net/eclipse', feature: 'net.mihai-nita.ansicon.feature.group' }
  - { repo: 'http://www.genuitec.com/updates/webclipse/oxygen/', feature: 'com.genuitec.eclipse.theming.feature.feature.group' }
  # Angular IDE plugin
  - { repo: 'https://www.genuitec.com/updates/webclipse/ci/', feature: 'com.genuitec.eclipse.angularide.feature.feature.group' }
  # LESS Plugin
  #- { repo: 'http://www.normalesup.org/~simonet/soft/ow/update', feature: 'net.vtst.ow.eclipse.less.feature' }
  # PHP Development Tools
  #- { repo: 'http://download.eclipse.org/tools/pdt/updates/5.3', feature: 'org.eclipse.php.feature.group' }
  # PHP Symphony
  #- { repo: 'http://p2.pdt-extensions.org/', feature: 'com.dubture.symfony.feature.feature.group' }
  # PHP restful
  #- { repo: 'http://p2.pdt-extensions.org/', feature: 'org.oneclicklabs.php.restful.feature.group' }
  ignore_errors: yes

- name: Make sure that the owner is set correctly
  tags: eclipse
  file:
    path: "{{ HOMEDIR }}/Tools/eclipse-{{ eclipse_release }}"
    owner: "{{ USERNAME }}"
    group: "{{ GROUPNAME }}"
    recurse: yes




