---

- name: Update apt packages
  become: yes
  tags: mysql
  apt:
    update_cache: yes

- name: Install mysql server and mysql workbench
  become: yes
  tags: mysql
  package:
    name: "{{ item }}"
    state: present
  with_items:
  - mysql-server
  - mysql-workbench
  - python-mysqldb

- name: update mysql root password for all root accounts
  become: yes
  tags: mysql
  mysql_user:
    name: root
    host: localhost
    password: 1234
