---

- name: Update apt packages
  become: yes
  tags: mysql
  apt:
    update_cache: yes

- name: Install mysql server and mysql workbench
  become: yes
  tags: mysql
  package:
    name: "{{ item }}"
    state: present
  with_items:
  - mysql-server
  - mysql-workbench