---

- name: Update apt packages
  become: true
  tags: mysql
  apt:
    update_cache: yes

- name: Install mysql server and mysql workbench
  become: true
  tags: mysql
  package:
    name: "{{ item }}"
    state: present
  with_items:
  - mysql-server
  - mysql-workbench

# TODO
#- name: Adding mysql vagrant user
#  become: yes
#  tags: mysql
#  mysql_user:
#    name: vagrant
#    password: vagrant
#    host: localhost
#    state: present
#    check_implicit_admin: yes
#    priv: "*.*:ALL"
#