---

- name: Install python/pip
  tags: azurecli
  become: true
  package:
    name: "{{ item }}"
    state: present
  loop:
    - python3
    - python3-pip

- name: Install azure cli
  tags: azurecli
  pip:
    name: azure-cli
    state: present

- name: Add another bin dir to system-wide $PATH.
  tags: azurecli
  become: true
  copy:
    dest: /etc/profile.d/local-path.sh
    content: 'PATH=$PATH:~/.local/bin'
    mode: 0644