---

- name: Download deb package
  get_url:
    url: "https://go.microsoft.com/fwlink/?LinkID=760868"
    dest: "/tmp/vscode.deb"

- name: Install vscode ...
  become: yes
  shell: "dpkg -i /tmp/vscode.deb"