---

- name: Ensure apt-transport-https is installed.
  apt:
    name: apt-transport-https
    state: present

- name: Add Nodesource apt key.
  apt_key:
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280
    id: "68576280"
    state: present

- name: Add NodeSource repositories for Node.js.
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "deb https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main"
    - "deb-src https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main"

- name: Update apt cache if repo was added.
  apt:
    update_cache: yes

- name: Install nodejs
  package:
    name: nodejs
    state: latest

#- name: Make link
#  file:
#    src: /usr/bin/node
#    dest: /usr/bin/nodejs
#    state: link

- name: Install npm packages
  npm:
    name: "{{ item }}"
    global: yes
    state: latest
  with_items:
  - npm
  - grunt
  - grunt-cli
  - yo
  - bower
  - generator-cg-angular
