---

- name: "Download soapui {{ soapui_version }} ..."
  tags: soapui
  register: task_result
  retries: "{{ RETRIES }}"
  delay: "{{ DELAY }}"
  until: "'OK' in task_result.msg or 'file already exists' in task_result.msg or 'HTTP Error 304: Not Modified' in task_result.msg"
  get_url:
    url: "{{ soapui_download_url }}"
    dest: /tmp/soapui.tar.gz

- name: Create directory
  become: true
  tags: soapui
  file:
    path: "{{ item }}"
    state: directory
  with_items:
  - /usr/local/soapui

- name: Unpack soapui
  become: true
  tags: soapui
  unarchive:
    src: /tmp/soapui.tar.gz
    dest: /usr/local/soapui/
    extra_opts: "--strip-components=1"
    owner: "{{ USERNAME }}"
    group: "{{ GROUPNAME }}"

- name: Download SoapUI icon
  become: true
  tags: soapui
  register: task_result
  retries: "{{ RETRIES }}"
  delay: "{{ DELAY }}"
  until: "'OK' in task_result.msg or 'file already exists' in task_result.msg or 'HTTP Error 304: Not Modified' in task_result.msg"
  get_url:
    url: "http://icons.iconarchive.com/icons/papirus-team/papirus-apps/512/soapui-icon.png"
    dest: /usr/local/soapui/soapui-icon.png

- name: Ensure that a desktop shortcut for soapui exists
  tags: soapui
  template:
    src: soapui.desktop.j2
    dest: "{{ HOMEDIR }}/Desktop/soapui.desktop"
    mode: 0755
    owner: "{{ USERNAME }}"
    group: "{{ GROUPNAME }}"
