---

- name: "Download microsoft packages ..."
  tags: dotnet
  register: task_result
  retries: "{{ RETRIES }}"
  delay: "{{ DELAY }}"
  get_url:
    url: https://packages.microsoft.com/config/ubuntu/21.04/packages-microsoft-prod.deb
    dest: /tmp/packages-microsoft-prod.deb
  until: "'OK' in task_result.msg or 'file already exists' in task_result.msg or 'HTTP Error 304: Not Modified' in task_result.msg"

- name: Install microsoft packages ...
  tags: dotnet
  become: yes
  command: dpkg -i /tmp/packages-microsoft-prod.deb

- name: Update apt packages
  tags: dotnet
  become: true
  apt:
    update_cache: yes

- name: Install required packages
  tags: dotnet
  become: yes
  package:
    name: "apt-transport-https"
    state: present

- name: Update apt packages
  tags: dotnet
  become: true
  apt:
    update_cache: yes

- name: Install dotnet-sdk-6.0 packages
  tags: dotnet
  become: yes
  package:
    name: "dotnet-sdk-6.0"
    state: present

