---

- name: Install required modules
  become: yes
  tags: maven
  package:
    name: "{{ item }}"
    state: present
  with_items:
  - default-jdk
  - openjdk-11-source

- name: Download latest maven
  tags: maven
  get_url:
    url: "{{ maven_download_url }}"
    dest: /tmp/maven.tar.gz

- name: Unpack maven
  tags: maven
  unarchive:
    src: /tmp/maven.tar.gz
    dest: "{{ homedir }}/Tools/"
    owner: "{{ username }}"
    group: "{{ groupname }}"

- name: Create maven link
  tags: maven
  file:
    src: "{{ homedir }}/Tools/apache-maven-{{ maven_version }}"
    dest: "{{ homedir }}/Tools/maven"
    state: link
    owner: "{{ username }}"
    group: "{{ groupname }}"

- name: Add maven to path
  tags: maven
  lineinfile:
   dest: "{{ homedir }}/.bashrc"
   state: present
   line: "export PATH={{ maven_path }}/bin:$PATH"

- name: Make sure that the owner is set correctly
  tags: maven
  file:
    path: "{{ homedir }}/Tools/apache-maven-{{ maven_version }}"
    owner: "{{ username }}"
    group: "{{ groupname }}"
    recurse: yes
