---

- name: Update apt packages
  tags: docker
  become: true
  apt:
    update_cache: yes
  
- name: Install required packages
  tags: docker
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items:
  - apt-transport-https
  - ca-certificates
  - curl
  - software-properties-common

- name: Add Docker GPG key
  tags: docker
  become: yes
  register: task_result
  retries: "{{ RETRIES }}"
  delay: "{{ DELAY }}"
  until: task_result is success
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Debug
  tags: docker
  debug:
    msg: "{{ task_result }}"

- name: 'add Docker repository'
  tags: docker
  become: true
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu impish stable'
    state: 'present'
    update_cache: 'yes'

- name: Update apt packages
  tags: docker
  become: true
  apt:
    update_cache: yes
  
- name: Install docker
  tags: docker
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items:
  - docker-ce
  - docker-ce-cli
  - containerd.io