---

- name: Upgrade all packages (Might take a few minutes)
  tags: default-packages
  become: true
  apt:
    update_cache: yes

- name: Install default packages
  tags: default-packages
  become: true
  package:
    name: "{{ item }}"
    state: latest
  with_items:
  - tree
  - gedit
  - htop
  - apache2
  - gimp
  - meld
  - tmux
  - curl
  - libnss3-tools     # for certutil
  - net-tools         # For ifconfig
