---

tomcat_version: 10.0.13
tomcat_download_url: "https://archive.apache.org/dist/tomcat/tomcat-10/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"
java_home: /usr/lib/jvm/default-java
catalina_home: /usr/share/tomcat/
catalina_base: /usr/share/tomcat/
tomcat_user: tomcat
jdbc_postgresql_version: 42.3.1
jdbc_postgresql_download_url: https://jdbc.postgresql.org/download/postgresql-{{ jdbc_postgresql_version }}.jar
